version: '3.9'

services:

  postgres:
    image: "postgres"
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
    ports:
        - "5434:5432"
    volumes:
        - ./create.sql:/docker-entrypoint-initdb.d/create.sql