version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: "postgres"
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
    ports:
        - "5432:5432"
    volumes:
        - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ivar.carrera@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "abc123"
    ports:
      - "15632:80"
    depends_on:
      - postgres